# Minimal stubs for essentia used in tests
from typing import Any

class MonoLoader:
    def __init__(self, filename: str) -> None: ...
    def __call__(self) -> Any: ...

class RhythmExtractor2013:
    def __init__(self, method: str = ...) -> None: ...
    def __call__(self, audio: Any) -> tuple: ...

class Windowing: ...
class Spectrum: ...
class Centroid: ...

# provide module-level version
__version__: str
