# Minimal type stubs for soundfile (pysoundfile)
from typing import Any, Tuple

def write(file: str, data: Any, samplerate: int) -> None: ...
def read(file: str) -> Tuple[Any, int]: ...
def info(file: str) -> Any: ...
