from typing import Any, Iterable, List, Tuple

class ID3:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def getall(self, key: str) -> List[Any]: ...
    def add(self, frame: Any, *args: Any, **kwargs: Any) -> None: ...
    def delall(self, key: str) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def items(self) -> Iterable[Tuple[str, Any]]: ...

class ID3NoHeaderError(Exception): ...
