# isort: skip_file
from typing import Any

from ._frames import (  # noqa: F401 - re-exported for typing
    APIC,
    TALB,
    TCON,
    TIT2,
    TPE1,
    TXXX,
)

from . import _frames  # noqa: F401 - ensure submodule is discoverable

class ID3:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def getall(self, key: str) -> list[Any]: ...
    def add(self, frame: Any, *args: Any, **kwargs: Any) -> None: ...
    def delall(self, key: str) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def items(self) -> list[tuple[str, Any]]: ...

class ID3NoHeaderError(Exception): ...
